Qminder/javascript-api

README.md
package.json
src/qminder-api.js

Add on-error callback arguments to almost every API call

---

README.md
package.json
src/qminder-api.js
test/tickets-spec.js

auditLogs API call

---

package.json
src/qminder-api.js

Add Qminder API to window, add version inside the module as well

---

package.json
src/qminder-api.js
test/tickets-spec.js

Fixes #80 
The user parameter is now optional for adding labels to tickets.

Optional user ID in tickets.addLabel

---

README.md
package.json
src/qminder-api.js

Methods for picture adding and deleting endpoints

---

README.md
package.json
src/qminder-api.js
test/tickets-spec.js

Markus issue 91

---

README.md
package.json
src/qminder-api.js
test/tickets-spec.js

Message sending endpoint

---

README.md
package.json
src/qminder-api.js
test/tickets-spec.js

Response scope for ticket search and deets

---

README.md
package.json
src/qminder-api.js
test/tickets-spec.js

Ticket time estimation endpoint

---

package-lock.json
package.json
src/model/Desk.js
src/model/Device.js
src/model/Line.js
src/model/Ticket.js
src/model/User.js

Fix typo, add @flow to get yelled at when typos happen

---

package-lock.json
package.json
src/api-base.js
test/web/ApiBase.test.js

Fixes #131
This issue was preventing any POST requests with JSON data going through.

Make sure to add URLencoded content-type when POSTing string data

---

package-lock.json
package.json
src/services/UserService.js
test/web/UserService.test.js

Fixes #133
However, more JSON requests may be out of place :)

Send a user's roles as a stringified JSON array on creating a new user.

---

package-lock.json
package.json
src/services/TicketService.js
test/web/TicketService.test.js

Fixes #141
Implement Ticket Count, as well as test to make sure that it generates the URLs correctly and calls the request method with the right parameters.

Add Ticket Count to services

---

docs/index.html
package-lock.json
package.json
src/services/TicketService.js
test/web/TicketService.test.js

This PR removes the user check from Qminder.tickets.addLabel(). Additionally, it adds three regression tests to make sure the bug stays down.
Fixes #147

Adding a label does not actually need a user

---

docs/index.html
package.json
src/services/TicketService.js
test/web/TicketService.test.js

Fix some API issues

---

package.json
src/services/TicketService.js
test/web/TicketService.test.js

Make sure TicketService.getMessages() uses the correct key from HTTP response

---

package.json
src/services/LineService.ts
test/web/LineService.test.js

Should wait until the endpoints and documentation are fully live before merging.
Resolve #229

Line enable/disable

---

package.json
yarn.lock

This PR updates RxJS to 6.5.2, fixing #234 :)

Update RxJS to 6.5.2, fixes #234

---

.travis.yml

This PR updates the API key used to publish this package to NPM.

Update Travis publish key

---

package.json
src/services/LineService.ts

Remove trailing slash from line creation

---

.github/workflows/release.yml

This PR updates the CI publish workflow a bit 😄

Update CI publisher

---

package.json
yarn.lock

This PR bumps RxJS to version 6.5.5.

Bump RxJS to 6.5.5

---

src/services/LineService.ts
test/web/LineService.test.js
yarn.lock

update method in LineService

---

src/services/GraphQLService.ts

Turns out it was caused by doing a GraphQL subscription but never actually subscribing to observable.
I made whole function lazy.
Fixes #267

fix(graphql): Error when subscribing to GraphQL events

---

.github/PULL_REQUEST_TEMPLATE/pull_request.md

This PR is made automatically, it adds the pull request templates required for Vanta.

Pull request template

---

.github/workflows/code-coverage.yml

Reporting code coverage on every build.

feature(build): reporting code coverage

---

package.json

This PR changes the package version.

chore: fix version

---

src/services/UserService.ts
test/unit/UserService.test.ts

This endpoint does not exist anymore.

feat(user): removed function for removing a user

---

src/services/LineService.ts
test/unit/LineService.test.ts

This PR adds unarchive and delete functions to the `LineService` and covers them with tests.

feat(line service): add unarchive and delete functions

---

package.json

Bump the version of the package after #320 to allow users to update to newest version
#320

Patch version bump: v6.0.1

---

src/model/ID.ts
src/model/Webhook.ts
src/services/WebhooksService.ts
test/unit/WebhooksService.test.ts

feat(webhooks): ID is String type

---

package.json

chore: version 7.0.0

---

package.json

chore: version 7.2.0

---

package.json

chore: version 7.3.0

---

package.json
yarn.lock

chore: bumb Typescript

---

package.json
yarn.lock

chore: bump isomorphic-fetch

---

package.json

chore: version 8.0.0

---

package.json

chore: version 9.0.0

---

src/services/UserService.ts
test/unit/UserService.test.ts

chore: removed endpoint for role adding

---

package.json

chore(verison): Bump to 9.0.1

---

package.json

chore(version): Bump 9.0.2

---

.github/workflows/release.yml

Remove argument.
Added issue to maube re-add it for @boxmein https://github.com/Qminder/javascript-api/issues/458

chore(tooling): Remove yarn install argument in release script

---

package.json

chore(version): Bump to 9.0.3

---

.github/workflows/release.yml

Fix publish script to work with yarn 3.
Use the same workflow as in [ui-components](https://github.com/Qminder/ui-components/blob/master/.github/workflows/release.yml#L38)

fix(tooling): Change publish script

---

package.json

chore(version): Bump 9.0.4

---

package.json

chore(version): Bump to 9.0.6

---

src/lib/services/graphql/graphql.service.ts

The current import statement in graphqlservice clashes with ESM runtime. Let's fix the import statement.

fix(imports): Change import

---

package.json

chore(version): Bump to 10.0.1

---

package.json

Bump version to 10.0.2 so we can publish the fix for the websocket problem (#544)

chore: bump to 10.0.2

---

package.json

chore(version): Bump to 11

---

src/lib/services/graphql/graphql.service.ts

When a websocket `error` event is fired, it includes the error message as well. Let's add it to logging.

feat: WebSocket error message logging

---

package.json

chore: bump to 11.0.1

---

package.json
src/public-api/model.ts

Exporting `TicketStatus` model.

feat: export TicketStatus

---

src/lib/services/graphql/graphql.service.ts

Sends a console log message with the close code and reason that a websocket was closed.

fix: log when websocket closes

---

examples/events/new-visitors.js

The example has drifted a bit from reality. This PR fixes the example to work with the current version of JS API.
Fixes #560

fix(docs): update new visitors example

---

package.json

Updates Javascript API version number to 11.1.1
Contains #577

chore: bump version to 11.1.1

---

package.json

Reasons:
* #599 improves the model
* #582 is more clear about errors
#582 #599

chore: bump to 11.2.0

---

package.json

chore: bump to 12.1.0

---

package.json

chore(version): Bump to 12.1.1

---

package.json

chore(version): bump to 12.1.2

---

package.json

chore: bumped version to 13.1.0

---

README.md
package.json

chore: bumped version to 13.3.0

---

package.json

chore: bumped version to 13.4.0

---

packages/javascript-api/package.json
packages/javascript-api/src/lib/services/graphql/graphql.service.ts

Solves a issue we are having with Cypress: https://github.com/cypress-io/cypress/issues/27599

chore: fully qualified import

---

packages/javascript-api/src/lib/model/ticket/external-data.ts
packages/javascript-api/src/lib/services/ticket/set-external-data.spec.ts
packages/javascript-api/src/lib/services/ticket/ticket.ts

Typescript type for setExternalData.
Matches the JSON schema that backend uses for validation.

feat: Typescript type for "setExternalData"

---

packages/javascript-api/package.json

chore(release): bump version to 15.1.1
