Qminder/javascript-api

- package.json
- src/qminder-bridge.js
This PR allows QminderBridge.showKeyboard to set the maximum input length that the iOS application requires. It's passed as an integer inside the URL, and the code doesn't yet assert the parameter is valid. It however defaults to 50 when nothing is provided.
This fixes #37
> add the input's max length as argument into QminderBridge.showKeyboard

- package.json
- src/qminder-api.js
This PR increases the amount of time the code waits before trying to reconnect to the websocket. Starting from 5 seconds, the new behaviour increments the wait time by a second every 10 retries up to a maximum of 60 seconds. If a successful connection is made, the wait time is reset.
> Auto-increase socket retry timeout every 10 tries

- package.json
- src/qminder-api.js
- src/qminder-bridge.js
This PR exposes two features:
(1) New API method to trigger a re-connection to the Qminder API events server. This method will automatically check if there is currently no connection, and if there isn't a pending connection.
(2) New Qminder Bridge method to pass events from the iOS app regarding the app's "active state" - whether the app is focused or not.
> Re-connection triggering + Bridge update

- package.json
- src/qminder-api.js
As well as that, error callbacks are now properly called out when `JSON.parse` throws an error.
Fixes #59
> Error callbacks receive original request and error event objects now

- package.json
- src/qminder-api.js
Fixes #61. Previously the "user" parameter was ignored, but now it isn't.
> Pass the user ID into the HTTP request

- package.json
- src/qminder-api.js
This PR changes the behaviour of request(). It no longer calls the success callback inside a try-catch block, meaning that errors raised by the success callback will not propagate upward as errors of the surrounding API call.
Fixes #87
> Make sure that JSON error handling will not catch callback errors

- package.json
- src/qminder-api.js
The API script will now check that a browser environment exists before doing user-agent matching to support the Samsung TV.
Fixes #97
> Don't assume a browser environment for WebSocket events

- package.json
- src/qminder-bridge.js
Fixes #113
This is useful for module loader support and lets us move to more modular ways of writing JS code.
> Add CommonJS export to Qminder Bridge

- package-lock.json
- package.json
- test/run-tests.sh
- test/web/EventsService.test.js
When tests fail, make sure to close mock server, because Travis will keep retrying to install.
> Always close mock server after tests

- .gitignore
- package.json
- scripts/build-full.sh
- scripts/build-web-unbundled.sh
This is for inclusion with jsnext:main-supporting module compilers such as Closure, which don't support UMD module definitions, but support ES6 modules.
> Build a second web distribution: unbundled & ES6

- .babelrc
- package-lock.json
- package.json
This allows API consumers to build Qminder API from ES6+Flow source to JS themselves, utilizing tree-shaking and other benefits.
> Do not ignore node_modules in .babelrc

- jasmine.json
- karma.conf.js
- package.json
- scripts/build-full.sh
- src/api-base.js
- test/mock-websocket-server.js
- test/node_helper.js
- test/run-node-tests.sh
- test/run-tests.sh
- test/web/ApiBase.test.js
- test/web/Configuration.test.js
- test/web/DeviceService.test.js
- test/web/EventsService.test.js
- test/web/LineService.test.js
- test/web/LocationService.test.js
- test/web/TicketService.test.js
- test/web/UserService.test.js
- test/web/WebhooksService.test.js
This PR fixes #156 - ApiBase.js tried to use File in determining the type of payload to send in POST requests.
Additionally, this PR sets up tests for Node.js - bringing with it a few changes to the test code, such as not entirely depending on global variables (Jasmine.js does not support that). 
Lastly, the PR improves stability of mock-websocket-server by waiting for both control & client sockets to be open before event tests, and by having the server clean up both ends of the socket if one drops.
> Setup Node.js testing & File API bugfix

- src/services/TicketService.js
- test/web/TicketService.test.js
This PR makes sure that TicketService#reorder sends the right payload when reordering to be first. Additionally, it makes sure that TicketService#reorder works with Ticket objects as it should.
Fixes #159
Fixes #158
> TicketService#reorder - reorder-first payload fix + Ticket object handling fix

- package.json
- src/services/EventsService.js
- test/web/EventsService.test.js
Turns out the data structure I used for keeping track of subscriptions (to re-subscribe when the socket reconnects) had double entries because both WebSocket#onopen and EventsService#createSubscription registered them into the subscriptions array.
Fixes #163
> Fix EventsService double subscriptions

- package.json
- src/services/TicketService.js
- test/web/TicketService.test.js
This PR makes sure that ApiBase.request sends a POST on Qminder.tickets.reorder, even if the payload is null / undefined.
Fixes #165
> Qminder.tickets.reorder always sends a POST now

- README.md
- package.json
- src/services/EventsService.js
- test/web/EventsService.test.js
This PR adds the last few fixes to prevent double-submitting SUBSCRIBE events in the Events API.
- Removes the messageQueue because the subscriptions list already fills the same purpose.
- Adds a test to actually verify subscribe call count
Fixes #163, and supplements #164
> Events API final fixes

- docs/index.html
- package.json
- src/services/EventsService.js
- test/node_helper.js
- test/web/EventsService.test.js
- test/web/LocationService.test.js
This PR implements Qminder.events.onLocationChanged.
Additionally, it enables two tests that could previously not have worked.
Lastly, it updates the documentation to match.
Fixes #168
> Qminder.events.onLocationChanged + 2 pending tests

- docs/index.html
- package.json
- src/services/TicketService.js
- test/web/TicketService.test.js
This PR implements TicketService.unassign.
This means that users can remove visitors being assigned to specific clerks.
Fixes #170
> TicketService.unassign implementation

- docs/index.html
- package.json
- src/model/User.js
- test/web/User.test.js
This PR adds a third utility function to the User model: isOwner().
Now, in order to check if a user has enough administrative privileges to perform certain actions, this logical clause should be used:
user.isAdmin() || user.isOwner()
In order to check access to owner-only actions, this clause can be used:
user.isOwner()
Fixes #175
> Add isOwner to User model as well

- karma.conf.js
- src/api-base.ts
Fixes #179 
It seems that our tests are currently order specific. This should be changed, since tests should be atomic and all that. The tests have been written in an atomic fashion, however the issue that we're facing with random ordered tests is that some tests try to Stub a method that has been currently stubbed by a different test.
This could be fixed by loading a fresh Qminder object somehow for every test (or having Karma reload the page after every test, or similar measures). In Node.js, the require.cache could be cleared and the object loaded again.
> Mark "random: false" in karma.conf, and remove a logging line.

- .travis.yml
This PR pushes the travis CI key update from 23 June 2018.
After merging this, we can move the v2.2.4 key to latest master, and redeploy v2.2.4.
> Update Travis CI key

- .gitignore
- src/services/GraphQLService.ts
Note: currently backend doesn't send subscription ID with errors in GraphQL subscriptions, this will have to wait on that.
> Added .idea to .gitignore and made GraphQL subscription error handling safer

- package.json
- yarn.lock
This PR makes it so that RxJS is a peer dependency of `qminder-api`. This change ensures that only one copy of RxJS is installed if a consumer of the JS API uses RxJS as well. 
Practically nothing changes, since RxJS is required to use GraphQL subscriptions - and consumers of that API already install it.
It should be safe to upgrade projects to use this, even those that don't use RxJS. However, we should still test during the upgrade - if everything works as expected.
> RxJS is now a peer dependency of javascript-api

- src/services/TicketService.ts
- test/web/TicketService.test.js
This PR does three things:
- Accepts user parameter for ticket editing and sends it onwards to the HTTP request
- Replaces ticket types with specific TicketCreateParameters / TicketEditParameters
- Accepts string ID for ticket
The unit tests reflect that and have been updated with the User check as well.
Fixes #255 
Fixes #244 
Fixes #193 
Fixes #150
> Simplify Ticket types and accept User for ticket editing, fixes #255

- src/services/GraphQLService.ts
- test/unit/GraphQLSubscriptions.test.ts
- yarn.lock
When the GraphQL Subscriptions websocket receives a message with an ID unknown to GraphQLService, it will throw an error.
This PR makes it so the GraphQL subscriptions websocket handler will ignore messages that don't match to a corresponding ID in GraphQL Service.
The most common way for this to occur is when a high-traffic location uses GraphQL subscriptions and unsubscribes from one message type, but a few messages are still in flight for that subscription.
> fix(graphql-subscriptions): Gracefully handle messages for a Subscription that doesn't exist in internal state

- src/graphql-batcher.ts
- test/unit/graphql-batcher.test.ts
GraphQL Batcher will no longer throw a ValueError while trying to access non-existent data, when the query errors.
Instead, it will pass the query errors (if present) to the downstream consumer for further processing. 
I created a new error class `GraphqlBatcherError` that stores the errors data from the API. The GraphQL Batcher will reject with an instance of GraphqlBatcherError when the query errors.
> fix(graphql-batcher): GraphQL Batcher will not error with "Cannot read property '0' of null" when error response is received

- docs/classes/_services_locationservice_.locationservice.html
- src/services/LocationService.ts
- test/unit/LocationService.test.ts
This PR removes a method for fetching location input fields since it is not a part of the public API anymore.
> refactor: remove `getInputFields` method

- package.json
- src/services/GraphQLService.ts
- test/unit/GraphQLService.test.ts
- test/unit/GraphQLSubscriptions.test.ts
- yarn.lock
This PR adds support for tagged GraphQL strings (popularized by frameworks like Apollo and Relay). It should help with syntax highlighting and validation during compilation / early runtime.
**Before:**
```typescript
// Supported as-is
Qminder.graphql.query("{ me { id } }")
// Breaking change highlighted below ⚠️ 
Qminder.graphql.query("changedTickets(...) { id }")
```
**After:**
```typescript
// this version will syntax-highlight, and do schema completion in most IDEs
Qminder.graphql.query(gql`{ me { id } }`)
Qminder.graphql.query(gql`subscription { changedTickets(...) { id } }`)
```
⚠️ As a related change, `subscription {` and `}` are no longer automatically added to .subscribe() calls for GraphQL subscriptions.
> Support tagged GraphQL strings (and other pre-parsed GraphQL) 

- src/api-base.ts
- src/util/errors.ts
- test/unit/ApiBase.test.ts
This PR changes the Qminder.graphql.query signature to reject the promise when the GraphQL API returns with errors.
A new error type was introduced, `GraphQLApiError`, which stores the message from the backend as the error's message.
This is a breaking change.
> feat(errors): GraphQL API errors are exposed as rejected promises

- src/services/GraphQLService.ts
This PR makes sure that `subscription {}` is not automatically added around subscriptions. It causes issues during reconnects or very early subscriptions.
Fixes #320
> Remove subscription {} from automatically being added

- package.json
- src/api-base.ts
- src/model/ClientError.ts
- src/qminder-api.ts
- test/unit/ApiBase.test.ts
We have new standardised error response type.
```json
{"error":{"email":"Email address is in use"},"statusCode":409}
```
> feat: handle new error response type

- package.json
- src/services/TicketService.ts
- test/unit/TicketService.test.ts
When creating ticket with lastName as `null` it actually creates ticket with last name set to "null".
Now we just omit the `null` value.
> fix: ticket creation will not send null as a last name

- src/api-base.ts
- src/services/TicketService.ts
- test/unit/TicketService.test.ts
This PR adds a feature to set ticket labels.
Closes #326
> feat: set ticket labels

- src/qminder-api.ts
- src/services/GraphQLService.ts
- test/unit/GraphQLSubscriptions.test.ts
This PR changes GraphQL API so that the provided API key is used to create a temporary API key. The newly created temporary key will be used to establish a web socket connection. In that way, we can mitigate https://github.com/Qminder/server/issues/15986.
Related to https://github.com/Qminder/server/issues/15986
> feat: use temporary api key to open ws connection

- src/api-base.ts
* Backend does not return `statusCode` anymore.
* `errors` is defined only when there are any errors.
> feat: updated response type for GraphQL

- docs/classes/tickets.html
- src/services/TicketService.ts
This PR removes position MIDDLE from docs and from type declaration DesiredQueuePosition.
Also refactors ticket return to queue event initialisation description.
Closes #378 
Related to https://github.com/Qminder/server/issues/16308
> feat(service): remove return to queue position MIDDLE

- src/api-base.ts
This PR sets GraphQL request header '`Content-Type`' to '`application/json`'
Testing how-to is specified in related issue.
Related to https://github.com/Qminder/server/issues/17013
> feat(api-base): set GraphQL request 'Content-Type' to 'application/json'

- .github/workflows/release.yml
Release failed with the following error
Let's try to use the same secret variable that works in ui-comp
https://github.com/Qminder/ui-components/blob/master/.github/workflows/release.yml#L40
> fix(tooling): Change env variable name

- src/services/GraphQLService.ts
> https://websockets.spec.whatwg.org//#message-example
This part of the websocket spec leads us to believe that the socket might be able to send an `onclose` event if the connection wasn't able to establish itself. Let's monitor if this really happens and if it does we can decide whether to 
- move the connection monitoring to the `onopen` event
- handle `onclose` event more accurately
> feat(graphql): Add connection error event

- tsconfig.json
During remote-sign-in-backend investigations I accidentally saw that we include our spec files with the output. Let's remove them.
> fix(CI): Exclude spec files from build

- src/lib/services/graphql/graphql.service.spec.ts
- src/lib/services/graphql/graphql.service.ts
When a client subscribes to multiple different events in rapid succession, this library will create multiple WebSockets because of #544 .
This PR makes sure only one WebSocket is created.
<details><summary>I also checked if the unit test actually works</summary>
The test successfully detects if multiple websockets / fetch calls were performed:
```
❯ git revert -n cd3d0b44398301b85990a7b50b5154146f1e060c
❯ yarn test graphql.service
FAIL  src/lib/services/graphql/graphql.service.spec.ts
GraphQL service
query
✓ calls ApiBase.queryGraph with the correct parameters (5 ms)
✓ calls ApiBase.queryGraph with both query & variables (1 ms)
✓ collapses whitespace and newlines (1 ms)
✓ throws when query is missing (18 ms)
tag support
✓ GraphqlService.query works correctly when passed a gql`` tagged …
```
> fix: only a single websocket is opened when subscribe() called in rapid succession

- src/lib/model/client-error.ts
- src/lib/model/errors/complex-error.ts
- src/lib/model/errors/simple-error.ts
- src/lib/model/errors/unknown-error.ts
- src/lib/services/api-base/api-base.spec.ts
- src/lib/services/api-base/api-base.ts
- src/lib/services/webhooks/webhook.service.ts
- src/lib/services/webhooks/webhook.ts
- src/lib/util/errors.ts
- src/public-api/model.ts
Current implementation of api-base.request() recognised errors by the returned `statusCode` property.
Webhook removal endpoint returned `status` instead of `statusCode`.
I asked Stanislav if the `status` property is the standard as of now. He said no and encouraged me to use the actual request status instead of statusCode from the returned json.
So I tried out the [MDN spec](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#checking_that_the_fetch_was_successful) way of checking the response status and it worked as expected.
One more thing: I changed the return type of the Webhook request to from `Promise<DeleteWebhookResponse>` to `Promise<void>`. There's no advantage in sending the responseCode instead of using Promise.resolve and Promise.reject callbacks.
Migration …
> fix(api-base): Fix network error handling

- src/lib/services/api-base/api-base.spec.ts
- src/lib/services/api-base/api-base.ts
- src/lib/services/device/device.ts
- src/lib/services/line/line.ts
- src/lib/services/ticket/ticket.service.spec.ts
- src/lib/services/ticket/ticket.ts
- src/lib/services/user/user.service.spec.ts
- src/lib/services/user/user.ts
- src/lib/services/webhooks/webhook.service.ts
- src/lib/services/webhooks/webhook.ts
- src/lib/services/webhooks/webhooks.service.spec.ts
This PR refactors api-base to allow passing custom headers while creating a new webhook endpoint.
> feat(webhooks): allow setting custom headers

- src/lib/services/graphql/__fixtures__/graphql-subscriptions-fixture.ts
- src/lib/services/graphql/__tests__/graphql-subscriptions.spec.ts
- src/lib/services/graphql/graphql.service.ts
Ensures that errors sent by the server to the client using GQL_ERROR messages are passed to the consumer of the library. The subscription is assumed to have never opened & internal state is cleaned up.
Connection closures and errors on establishing the connection are logged and otherwise not passed to the consumer, in order to be able to restore connectivity without completing all of the existing Observables.
Fixes #580 
Fixes #217
> fix: subscription errors propagated to consumers

- src/lib/services/graphql/__fixtures__/graphql-subscriptions-fixture.ts
- src/lib/services/graphql/__tests__/graphql-subscriptions-jsdom-only.spec.ts
- src/lib/services/graphql/__tests__/graphql-subscriptions.spec.ts
- src/lib/services/graphql/graphql.service.ts
If the WebSocket is closed with a close code of 1000, but there are still open listeners, reconnect to the backend.
We think this could be a fix for #601 
#601
> fix: when there are open subscriptions, reconnect even on a close code of 1000

- src/lib/model/fetch.ts
- src/lib/model/ticket/ticket-creation-request.ts
- src/lib/services/api-base/api-base.ts
- src/lib/services/graphql/graphql.service.ts
Fixes a few issues in the ticket creation update:
* using `this.fetch = fetch;` in graphql.service.ts accidentally reassigns `this` in the fetch body, causing an Illegal invocation error
* lastName can be undefined / not present
#603
> fix: Fixes to ticket creation update

- src/lib/services/ticket/ticket.service.spec.ts
- src/lib/services/ticket/ticket.ts
Reaction to this PR: https://github.com/Qminder/server/pull/20023
Will change the ticket request endpoint from `/ticket/` to `/tickets/`
> feat(tickets): Change ticket creation endpoint url

- src/lib/model/ticket/ticket-creation-request.ts
Add languageCode to TicketCreationRequest as:
- defined in `com/qminder/api/controller/tickets/creation/TicketCreationControllerV2.kt:118`
- tested in Dashboard
https://github.com/user-attachments/assets/951f01c5-c35d-43d1-9525-8cfa6477994b
> feat(ticket): Add languageCode to TicketCreationRequest

- package.json
- src/lib/services/graphql/__fixtures__/graphql-subscriptions-fixture.ts
- src/lib/services/graphql/__tests__/graphql-subscriptions-jsdom-only.spec.ts
- src/lib/services/graphql/__tests__/graphql-subscriptions.spec.ts
- yarn.lock
No functional changes.
Added simple test before I start fixing bugs.
> feat(tests): test for fetching temporary API key

- src/lib/services/graphql/__fixtures__/graphql-subscriptions-fixture.ts
- src/lib/services/graphql/__tests__/graphql-subscriptions-jsdom-only.spec.ts
- src/lib/services/graphql/__tests__/graphql-subscriptions.spec.ts
- src/lib/services/graphql/graphql.service.ts
- src/lib/services/temporary-api-key/temporary-api-key.service.spec.ts
- src/lib/services/temporary-api-key/temporary-api-key.service.ts
Fixes:
* Does not retry when server responds with status `403`
* Retries when status is `500` or higher
* Tests if the response contains `key`
Refactored whole temporary API key fetching to a separate service
> fix: validating fetched temporary API key

- src/lib/services/temporary-api-key/temporary-api-key.service.spec.ts
- src/lib/services/temporary-api-key/temporary-api-key.service.ts
> fix: return temporary API key

- packages/javascript-api/package.json
- packages/javascript-api/src/lib/model/errors/response-validation-error.ts
- packages/javascript-api/src/lib/model/ticket/ticket-created-response.ts
- packages/javascript-api/src/lib/services/ticket/ticket.service.spec.ts
- packages/javascript-api/src/lib/services/ticket/ticket.ts
- packages/javascript-api/src/public-api/model.ts
* Testing if ticket creation response contains `id`
* Refactored `id` to be always a `string`
* Introduced new typed error `ResponseValidationError`
* Bumped version to `14.0.0` because of the changed return type
> feat: validating if ticket creation has expected response body

- packages/javascript-api/src/lib/services/ticket/ticket.service.spec.ts
- packages/javascript-api/src/lib/services/ticket/ticket.ts
There was a logic error in label removal.
Providing User should be optional.
> fix: removing label without providing user

- packages/javascript-api/src/lib/services/graphql/graphql.service.ts
No functional changes, improves developer experience.
> feat: generics for GraphQL subscriptions

- .gitignore
- packages/javascript-api/src/lib/services/graphql/graphql.service.ts
Remember connection status without subscribers.
Includes:
- Add `nohup.out` (generated by `qminder bind-javascript-api`) to `.gitignore`.
Necessary for [GraphQL is disconnected when creating a new account](https://github.com/Qminder/server/issues/26195).
> feat(`graphql`): remember connection status without subscribers
